package com.example.ainotessummarizer.Fragments;

import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.example.ainotessummarizer.ChatActivity;
import com.example.ainotessummarizer.R;
import com.example.ainotessummarizer.session.SessionManager;
import com.example.ainotessummarizer.storage.FlashcardStorage;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.android.material.card.MaterialCardView;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

/**
 * Home tab — greeting, live dashboard counters, and quick-action cards.
 *
 * Counter sources (verified against actual write paths):
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  🃏 Flashcards → FlashcardStorage (SharedPreferences, local)            │
 * │     Prefs key : "flashcard_prefs" / "flashcard_sets"                    │
 * │     Count     : list.size() — number of flashcard sets created           │
 * │                                                                          │
 * │  📝 Summaries  → Firebase: UserChats/{safeEmail}/sessions/ (child count) │
 * │     Each chat session = one summary session generated by AI              │
 * │                                                                          │
 * │  🤖 AI Chats   → Firebase: UserChats/{safeEmail}/sessions/ (child count) │
 * │     Each child = one conversation thread (matches ChatActivity drawer)    │
 * │                                                                          │
 * │  safeEmail = email.replace(".", "_").replace("@", "_at_")                │
 * │  (Must match ChatActivity.java line 163 exactly)                         │
 * └─────────────────────────────────────────────────────────────────────────┘
 */
public class HomeFragment extends Fragment {

    private static final String USER_CHATS_NODE = "UserChats";
    private static final String SESSIONS_NODE   = "sessions";

    // Firebase references held so listeners can be removed cleanly
    private DatabaseReference refSessions;
    private ValueEventListener sessionsListener;

    // Cached root view for stat updates
    private View rootView;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fragment_home, container, false);
        return rootView;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        SessionManager session = new SessionManager(requireContext());

        setupGreeting(view);
        setupUserName(view, session);
        setupProfileIcon(view);
        setupChatNavigation(view);
        setupQuickActions(view);
        setupSearchBar(view);

        // ── Load flashcard count immediately from local storage ──────────────
        refreshFlashcardCount();

        // ── Attach Firebase real-time listener for chat/summaries count ──────
        attachChatSessionsListener(session);
    }

    @Override
    public void onResume() {
        super.onResume();
        // Refresh local flashcard count every time the fragment becomes visible,
        // so the number is up-to-date after the user creates new flashcards.
        refreshFlashcardCount();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Flashcards — local SharedPreferences (FlashcardStorage)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Reads flashcard sets from SharedPreferences and updates the counter.
     * No Firebase involved — flashcards are stored locally.
     */
    private void refreshFlashcardCount() {
        if (!isAdded() || rootView == null) return;
        int count = FlashcardStorage.getFlashcardSets(requireContext()).size();
        TextView tv = rootView.findViewById(R.id.tvStatFlashcards);
        if (tv != null) tv.setText(String.valueOf(count));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // AI Chats & Summaries — Firebase Realtime Database
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Attaches a single ValueEventListener to UserChats/{safeEmail}/sessions/.
     *
     * One listener drives BOTH the Summaries and AI Chats counters because
     * each session node IS a summary session (one chat → one AI summary).
     *
     * safeEmail encoding MUST match ChatActivity.java:
     *   email.replace(".", "_").replace("@", "_at_")
     */
    private void attachChatSessionsListener(SessionManager session) {
        String email = session.getUserEmail();
        if (email == null || !email.contains("@")) return;

        // Match ChatActivity.java line 163 exactly
        String safeEmail = email.replace(".", "_").replace("@", "_at_");

        refSessions = FirebaseDatabase.getInstance()
                .getReference(USER_CHATS_NODE)
                .child(safeEmail)
                .child(SESSIONS_NODE);

        sessionsListener = new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                if (!isAdded() || rootView == null) return;
                long sessionCount = snapshot.getChildrenCount();

                // Summaries = number of sessions (each session generates one summary)
                TextView tvSummaries = rootView.findViewById(R.id.tvStatSummaries);
                if (tvSummaries != null) tvSummaries.setText(String.valueOf(sessionCount));

                // AI Chats = number of conversation threads (same sessions node)
                TextView tvChats = rootView.findViewById(R.id.tvStatChats);
                if (tvChats != null) tvChats.setText(String.valueOf(sessionCount));
            }

            @Override
            public void onCancelled(@NonNull DatabaseError error) {
                // Silent — counter stays at 0 if read fails
            }
        };

        refSessions.addValueEventListener(sessionsListener);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Listener cleanup — prevent memory leaks when fragment is destroyed
    // ─────────────────────────────────────────────────────────────────────────

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (refSessions != null && sessionsListener != null) {
            refSessions.removeEventListener(sessionsListener);
        }
        rootView = null;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // UI Setup helpers
    // ─────────────────────────────────────────────────────────────────────────

    private void setupGreeting(View view) {
        TextView tvGreeting = view.findViewById(R.id.tvGreeting);
        if (tvGreeting == null) return;
        int hour = java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY);
        String greeting;
        if (hour < 12)      greeting = "Good morning 👋";
        else if (hour < 17) greeting = "Good afternoon 👋";
        else                greeting = "Good evening 👋";
        tvGreeting.setText(greeting);
    }

    private void setupUserName(View view, SessionManager session) {
        TextView tvUserName = view.findViewById(R.id.tvUserName);
        if (tvUserName == null) return;
        String email = session.getUserEmail();
        if (email != null && email.contains("@")) {
            String name = email.substring(0, email.indexOf('@'));
            name = Character.toUpperCase(name.charAt(0)) + name.substring(1);
            tvUserName.setText(name + "'s Notes");
        }
    }

    private void setupProfileIcon(View view) {
        android.widget.ImageView ivProfile = view.findViewById(R.id.ivProfile);
        if (ivProfile != null)
            ivProfile.setOnClickListener(v -> navigateToTab(R.id.nav_profile));
    }

    private void setupChatNavigation(View view) {
        View cardStartAI = view.findViewById(R.id.cardStartAI);
        if (cardStartAI != null) cardStartAI.setOnClickListener(v -> openChat());

        View btnStart = view.findViewById(R.id.btnStart);
        if (btnStart != null) btnStart.setOnClickListener(v -> openChat());

        MaterialCardView cardChatAI = view.findViewById(R.id.cardChatAI);
        if (cardChatAI != null) cardChatAI.setOnClickListener(v -> openChat());
    }

    private void setupQuickActions(View view) {
        MaterialCardView cardHistory = view.findViewById(R.id.cardHistory);
        if (cardHistory != null)
            cardHistory.setOnClickListener(v -> navigateToTab(R.id.nav_history));

        MaterialCardView cardBookmarks = view.findViewById(R.id.cardBookmarks);
        if (cardBookmarks != null)
            cardBookmarks.setOnClickListener(v -> navigateToTab(R.id.nav_history));
    }

    private void setupSearchBar(View view) {
        View searchBar = view.findViewById(R.id.searchBarContainer);
        if (searchBar != null)
            searchBar.setOnClickListener(v -> navigateToTab(R.id.nav_history));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Navigation helpers
    // ─────────────────────────────────────────────────────────────────────────

    private void navigateToTab(int menuItemId) {
        if (getActivity() == null) return;
        BottomNavigationView nav = getActivity().findViewById(R.id.bottomNavigation);
        if (nav != null) nav.setSelectedItemId(menuItemId);
    }

    private void openChat() {
        startActivity(new Intent(requireActivity(), ChatActivity.class));
        if (getActivity() != null)
            getActivity().overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
    }
}
